// Servicio para generar plantillas CloudFormation
// Convierte diagramas de infraestructura en templates de CF listos para usar

/**
 * Generar plantilla CloudFormation completa desde un diagrama
 */
export function generateCloudFormationTemplate(diagram, config = {}) {
  const template = {
    AWSTemplateFormatVersion: '2010-09-09',
    Description: `Infrastructure for ${config.projectName || 'Application'} - Generated by AWS Mastery AI`,
    Parameters: generateParameters(config),
    Resources: {},
    Outputs: {}
  }

  // Generar recursos según los nodos del diagrama
  diagram.nodes.forEach(node => {
    const resource = generateResource(node, config)
    if (resource) {
      Object.assign(template.Resources, resource)
    }
  })

  // Generar conexiones/relaciones (security groups, IAM, etc.)
  diagram.connections.forEach(conn => {
    const connectionResources = generateConnectionResources(conn, diagram.nodes, config)
    if (connectionResources) {
      Object.assign(template.Resources, connectionResources)
    }
  })

  // Generar outputs útiles
  template.Outputs = generateOutputs(template.Resources)

  return template
}

/**
 * Generar parámetros del template
 */
function generateParameters(config) {
  return {
    Environment: {
      Type: 'String',
      Default: config.environment || 'dev',
      AllowedValues: ['dev', 'staging', 'prod'],
      Description: 'Deployment environment'
    },
    ProjectName: {
      Type: 'String',
      Default: config.projectName || 'myapp',
      Description: 'Name of the project'
    },
    VpcId: {
      Type: 'AWS::EC2::VPC::Id',
      Description: 'VPC ID'
    },
    SubnetIds: {
      Type: 'List<AWS::EC2::Subnet::Id>',
      Description: 'Subnet IDs'
    },
    KeyPairName: {
      Type: 'AWS::EC2::KeyPair::KeyName',
      Description: 'EC2 Key Pair for SSH access',
      ConstraintDescription: 'Must be an existing EC2 KeyPair'
    }
  }
}

/**
 * Generar un recurso AWS según el tipo de nodo
 */
function generateResource(node, config) {
  const resources = {}
  const resourceName = sanitizeResourceName(node.label || node.type)
  const tags = [
    { Key: 'Name', Value: { Ref: 'ProjectName' } },
    { Key: 'Environment', Value: { Ref: 'Environment' } },
    { Key: 'ManagedBy', Value: 'CloudFormation' }
  ]

  switch (node.type) {
    case 'vpc':
      resources[resourceName] = {
        Type: 'AWS::EC2::VPC',
        Properties: {
          CidrBlock: '10.0.0.0/16',
          EnableDnsHostnames: true,
          EnableDnsSupport: true,
          Tags: [...tags, { Key: 'Name', Value: `${config.projectName}-vpc` }]
        }
      }
      break

    case 'ec2':
    case 'asg':
      resources[resourceName + 'LaunchTemplate'] = {
        Type: 'AWS::EC2::LaunchTemplate',
        Properties: {
          LaunchTemplateName: `${config.projectName}-template`,
          LaunchTemplateData: {
            ImageId: getLatestAMI(config.os || 'amazon-linux-2'),
            InstanceType: config.instanceType || 't3.medium',
            KeyName: { Ref: 'KeyPairName' },
            SecurityGroupIds: [{ Ref: resourceName + 'SecurityGroup' }],
            UserData: {
              'Fn::Base64': generateUserData(config)
            },
            TagSpecifications: [{
              ResourceType: 'instance',
              Tags: tags
            }]
          }
        }
      }
      
      resources[resourceName] = {
        Type: 'AWS::AutoScaling::AutoScalingGroup',
        Properties: {
          VPCZoneIdentifier: { Ref: 'SubnetIds' },
          LaunchTemplate: {
            LaunchTemplateId: { Ref: resourceName + 'LaunchTemplate' },
            Version: { 'Fn::GetAtt': [resourceName + 'LaunchTemplate', 'LatestVersionNumber'] }
          },
          MinSize: config.minSize || 2,
          MaxSize: config.maxSize || 6,
          DesiredCapacity: config.desiredCapacity || 2,
          TargetGroupARNs: node.connectsTo?.includes('alb') ? [{ Ref: 'ALBTargetGroup' }] : [],
          Tags: [{
            Key: 'Name',
            Value: `${config.projectName}-asg`,
            PropagateAtLaunch: true
          }]
        }
      }
      
      resources[resourceName + 'SecurityGroup'] = {
        Type: 'AWS::EC2::SecurityGroup',
        Properties: {
          GroupDescription: `Security group for ${config.projectName}`,
          VpcId: { Ref: 'VpcId' },
          SecurityGroupIngress: [
            {
              IpProtocol: 'tcp',
              FromPort: 80,
              ToPort: 80,
              SourceSecurityGroupId: node.connectsTo?.includes('alb') ? { Ref: 'ALBSecurityGroup' } : { 'Fn::Cidr': ['0.0.0.0/0', 6, 8] }
            },
            {
              IpProtocol: 'tcp',
              FromPort: 443,
              ToPort: 443,
              SourceSecurityGroupId: node.connectsTo?.includes('alb') ? { Ref: 'ALBSecurityGroup' } : { 'Fn::Cidr': ['0.0.0.0/0', 6, 8] }
            }
          ],
          Tags: tags
        }
      }
      break

    case 'alb':
      resources[resourceName] = {
        Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
        Properties: {
          Name: `${config.projectName}-alb`,
          Scheme: 'internet-facing',
          Type: 'application',
          Subnets: { Ref: 'SubnetIds' },
          SecurityGroups: [{ Ref: resourceName + 'SecurityGroup' }],
          Tags: tags
        }
      }
      
      resources[resourceName + 'SecurityGroup'] = {
        Type: 'AWS::EC2::SecurityGroup',
        Properties: {
          GroupDescription: 'ALB Security Group',
          VpcId: { Ref: 'VpcId' },
          SecurityGroupIngress: [
            { IpProtocol: 'tcp', FromPort: 80, ToPort: 80, CidrIp: '0.0.0.0/0' },
            { IpProtocol: 'tcp', FromPort: 443, ToPort: 443, CidrIp: '0.0.0.0/0' }
          ],
          Tags: tags
        }
      }
      
      resources[resourceName + 'TargetGroup'] = {
        Type: 'AWS::ElasticLoadBalancingV2::TargetGroup',
        Properties: {
          Name: `${config.projectName}-tg`,
          Port: 80,
          Protocol: 'HTTP',
          VpcId: { Ref: 'VpcId' },
          TargetType: 'instance',
          HealthCheckPath: config.healthCheckPath || '/health',
          HealthCheckIntervalSeconds: 30,
          HealthyThresholdCount: 2,
          UnhealthyThresholdCount: 3,
          Tags: tags
        }
      }
      
      resources[resourceName + 'Listener'] = {
        Type: 'AWS::ElasticLoadBalancingV2::Listener',
        Properties: {
          DefaultActions: [{
            Type: 'forward',
            TargetGroupArn: { Ref: resourceName + 'TargetGroup' }
          }],
          LoadBalancerArn: { Ref: resourceName },
          Port: 80,
          Protocol: 'HTTP'
        }
      }
      break

    case 'rds':
      resources[resourceName + 'SubnetGroup'] = {
        Type: 'AWS::RDS::DBSubnetGroup',
        Properties: {
          DBSubnetGroupDescription: `Subnet group for ${config.projectName}`,
          SubnetIds: { Ref: 'SubnetIds' },
          Tags: tags
        }
      }
      
      resources[resourceName + 'SecurityGroup'] = {
        Type: 'AWS::EC2::SecurityGroup',
        Properties: {
          GroupDescription: 'RDS Security Group',
          VpcId: { Ref: 'VpcId' },
          SecurityGroupIngress: [{
            IpProtocol: 'tcp',
            FromPort: 5432,
            SourceSecurityGroupId: { Ref: 'EC2SecurityGroup' }
          }],
          Tags: tags
        }
      }
      
      resources[resourceName] = {
        Type: 'AWS::RDS::DBInstance',
        Properties: {
          DBInstanceIdentifier: `${config.projectName}-db`,
          DBName: config.dbName || 'appdatabase',
          Engine: config.dbEngine || 'postgres',
          EngineVersion: config.dbVersion || '15.4',
          DBInstanceClass: config.dbInstanceClass || 'db.t3.micro',
          AllocatedStorage: config.dbStorage || 20,
          StorageType: 'gp3',
          MasterUsername: { Ref: 'DBUsername' },
          MasterUserPassword: { Ref: 'DBPassword' },
          VPCSecurityGroups: [{ Ref: resourceName + 'SecurityGroup' }],
          DBSubnetGroupName: { Ref: resourceName + 'SubnetGroup' },
          BackupRetentionPeriod: 7,
          MultiAZ: config.environment === 'prod',
          StorageEncrypted: true,
          DeletionProtection: config.environment === 'prod',
          Tags: tags
        }
      }
      break

    case 's3':
      resources[resourceName] = {
        Type: 'AWS::S3::Bucket',
        Properties: {
          BucketName: `${config.projectName}-data-${config.accountId}`,
          VersioningConfiguration: { Status: 'Enabled' },
          BucketEncryption: {
            ServerSideEncryptionConfiguration: [{
              ServerSideEncryptionByDefault: {
                SSEAlgorithm: 'AES256'
              }
            }]
          },
          PublicAccessBlockConfiguration: {
            BlockPublicAcls: true,
            BlockPublicPolicy: true,
            IgnorePublicAcls: true,
            RestrictPublicBuckets: true
          },
          LifecycleConfiguration: {
            Rules: [{
              Id: 'TransitionToIA',
              Status: 'Enabled',
              TransitionInDays: 90,
              StorageClass: 'STANDARD_IA'
            }, {
              Id: 'TransitionToGlacier',
              Status: 'Enabled',
              TransitionInDays: 365,
              StorageClass: 'GLACIER'
            }]
          },
          Tags: tags
        }
      }
      break

    case 'lambda':
      resources[resourceName + 'ExecutionRole'] = {
        Type: 'AWS::IAM::Role',
        Properties: {
          AssumeRolePolicyDocument: {
            Version: '2012-10-17',
            Statement: [{
              Effect: 'Allow',
              Principal: { Service: 'lambda.amazonaws.com' },
              Action: 'sts:AssumeRole'
            }]
          },
          ManagedPolicyArns: [
            'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
          ],
          Tags: tags
        }
      }
      
      resources[resourceName] = {
        Type: 'AWS::Lambda::Function',
        Properties: {
          FunctionName: `${config.projectName}-function`,
          Runtime: config.runtime || 'nodejs20.x',
          Handler: 'index.handler',
          Role: { 'Fn::GetAtt': [resourceName + 'ExecutionRole', 'Arn'] },
          Code: {
            ZipFile: 'exports.handler = async (event) => { return { statusCode: 200, body: "Hello" }; };'
          },
          MemorySize: config.lambdaMemory || 512,
          Timeout: config.lambdaTimeout || 30,
          Environment: {
            Variables: {
              NODE_ENV: { Ref: 'Environment' }
            }
          },
          Tags: tags
        }
      }
      break

    case 'api':
      resources[resourceName] = {
        Type: 'AWS::ApiGateway::RestApi',
        Properties: {
          Name: `${config.projectName}-api`,
          Description: `API Gateway for ${config.projectName}`,
          EndpointConfiguration: {
            Types: ['EDGE']
          },
          Tags: tags
        }
      }
      
      resources[resourceName + 'Deployment'] = {
        Type: 'AWS::ApiGateway::Deployment',
        DependsOn: resourceName + 'RootMethod',
        Properties: {
          RestApiId: { Ref: resourceName },
          StageName: { Ref: 'Environment' }
        }
      }
      break

    case 'ecs':
    case 'fargate':
      resources[resourceName + 'Cluster'] = {
        Type: 'AWS::ECS::Cluster',
        Properties: {
          ClusterName: `${config.projectName}-cluster`,
          CapacityProviders: node.type === 'fargate' ? ['FARGATE', 'FARGATE_SPOT'] : ['EC2'],
          Tags: tags
        }
      }
      
      resources[resourceName + 'TaskExecutionRole'] = {
        Type: 'AWS::IAM::Role',
        Properties: {
          AssumeRolePolicyDocument: {
            Version: '2012-10-17',
            Statement: [{
              Effect: 'Allow',
              Principal: { Service: 'ecs-tasks.amazonaws.com' },
              Action: 'sts:AssumeRole'
            }]
          },
          ManagedPolicyArns: [
            'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
          ],
          Tags: tags
        }
      }
      
      resources[resourceName + 'TaskDefinition'] = {
        Type: 'AWS::ECS::TaskDefinition',
        Properties: {
          Family: `${config.projectName}-task`,
          NetworkMode: node.type === 'fargate' ? 'awsvpc' : 'bridge',
          RequiresCompatibilities: node.type === 'fargate' ? ['FARGATE'] : ['EC2'],
          Cpu: config.taskCpu || '256',
          Memory: config.taskMemory || '512',
          ExecutionRoleArn: { 'Fn::GetAtt': [resourceName + 'TaskExecutionRole', 'Arn'] },
          ContainerDefinitions: [{
            Name: `${config.projectName}-container`,
            Image: `${config.accountId}.dkr.ecr.${config.region}.amazonaws.com/${config.projectName}:latest`,
            PortMappings: [{
              ContainerPort: config.containerPort || 80,
              Protocol: 'tcp'
            }],
            LogConfiguration: {
              LogDriver: 'awslogs',
              Options: {
                'awslogs-group': { Ref: resourceName + 'LogGroup' },
                'awslogs-region': { Ref: 'AWS::Region' },
                'awslogs-stream-prefix': 'ecs'
              }
            }
          }],
          Tags: tags
        }
      }
      
      resources[resourceName + 'LogGroup'] = {
        Type: 'AWS::Logs::LogGroup',
        Properties: {
          LogGroupName: `/ecs/${config.projectName}`,
          RetentionInDays: 30,
          Tags: tags
        }
      }
      break

    case 'elasticache':
      resources[resourceName + 'SubnetGroup'] = {
        Type: 'AWS::ElastiCache::SubnetGroup',
        Properties: {
          Description: `Subnet group for ${config.projectName} cache`,
          SubnetIds: { Ref: 'SubnetIds' }
        }
      }
      
      resources[resourceName + 'SecurityGroup'] = {
        Type: 'AWS::EC2::SecurityGroup',
        Properties: {
          GroupDescription: 'ElastiCache Security Group',
          VpcId: { Ref: 'VpcId' },
          SecurityGroupIngress: [{
            IpProtocol: 'tcp',
            FromPort: 6379,
            SourceSecurityGroupId: { Ref: 'EC2SecurityGroup' }
          }],
          Tags: tags
        }
      }
      
      resources[resourceName] = {
        Type: 'AWS::ElastiCache::ReplicationGroup',
        Properties: {
          ReplicationGroupId: `${config.projectName}-cache`,
          ReplicationGroupDescription: `Redis cache for ${config.projectName}`,
          Engine: 'redis',
          CacheNodeType: config.cacheInstanceType || 'cache.t3.micro',
          NumCacheClusters: config.environment === 'prod' ? 2 : 1,
          AutomaticFailoverEnabled: config.environment === 'prod',
          MultiAZEnabled: config.environment === 'prod',
          CacheSubnetGroupName: { Ref: resourceName + 'SubnetGroup' },
          SecurityGroupIds: [{ Ref: resourceName + 'SecurityGroup' }],
          AtRestEncryptionEnabled: true,
          TransitEncryptionEnabled: true,
          Tags: tags
        }
      }
      break

    case 'sqs':
      resources[resourceName] = {
        Type: 'AWS::SQS::Queue',
        Properties: {
          QueueName: `${config.projectName}-queue.fifo`,
          FifoQueue: true,
          ContentBasedDeduplication: true,
          VisibilityTimeout: 300,
          MessageRetentionPeriod: 1209600,
          Tags: tags
        }
      }
      break

    case 'sns':
      resources[resourceName] = {
        Type: 'AWS::SNS::Topic',
        Properties: {
          TopicName: `${config.projectName}-notifications`,
          Tags: tags
        }
      }
      break

    case 'cdn':
      resources[resourceName] = {
        Type: 'AWS::CloudFront::Distribution',
        Properties: {
          DistributionConfig: {
            Origins: [{
              DomainName: node.connectsTo?.includes('s3') 
                ? { 'Fn::GetAtt': ['S3Bucket', 'DomainName'] }
                : { 'Fn::GetAtt': ['ALB', 'DNSName'] },
              Id: 'Origin1',
              S3OriginConfig: node.connectsTo?.includes('s3') ? {
                OriginAccessIdentity: ''
              } : undefined,
              CustomOriginConfig: !node.connectsTo?.includes('s3') ? {
                HTTPPort: 80,
                HTTPSPort: 443,
                OriginProtocolPolicy: 'https-only'
              } : undefined
            }],
            Enabled: true,
            DefaultCacheBehavior: {
              TargetOriginId: 'Origin1',
              ViewerProtocolPolicy: 'redirect-to-https',
              AllowedMethods: ['GET', 'HEAD', 'OPTIONS', 'PUT', 'POST', 'PATCH', 'DELETE'],
              CachedMethods: ['GET', 'HEAD'],
              ForwardedValues: {
                QueryString: true,
                Cookies: { Forward: 'none' }
              },
              MinTTL: 0,
              DefaultTTL: 86400,
              MaxTTL: 31536000
            },
            PriceClass: 'PriceClass_100',
            Tags: tags
          }
        }
      }
      break
  }

  return resources
}

/**
 * Generar recursos para conexiones entre nodos
 */
function generateConnectionResources(connection, nodes, config) {
  // Ya se manejan en los recursos individuales
  return null
}

/**
 * Generar outputs útiles
 */
function generateOutputs(resources) {
  const outputs = {}
  
  if (resources.ALB) {
    outputs.LoadBalancerURL = {
      Description: 'URL of the load balancer',
      Value: { 'Fn::Join': ['', ['http://', { 'Fn::GetAtt': ['ALB', 'DNSName'] }]] }
    }
  }
  
  if (resources.RDS) {
    outputs.DatabaseEndpoint = {
      Description: 'RDS Database endpoint',
      Value: { 'Fn::GetAtt': ['RDS', 'Endpoint.Address'] }
    }
  }
  
  if (resources.ECSCluster) {
    outputs.ClusterName = {
      Description: 'ECS Cluster Name',
      Value: { Ref: 'ECSCluster' }
    }
  }
  
  return outputs
}

/**
 * Sanitizar nombre para CloudFormation
 */
function sanitizeResourceName(name) {
  return name
    .replace(/[^a-zA-Z0-9]/g, '')
    .replace(/^[0-9]/, 'N')
    .substring(0, 64)
}

/**
 * Obtener AMI más reciente
 */
function getLatestAMI(os) {
  const amis = {
    'amazon-linux-2': 'ami-0c55b159cbfafe1f0',
    'amazon-linux-2023': 'ami-0c02fb55956c7d316',
    'ubuntu-22': 'ami-0c7217cdde317cfec',
    'ubuntu-20': 'ami-0a0e5d9c7acc336f1'
  }
  return amis[os] || amis['amazon-linux-2']
}

/**
 * Generar user data para EC2
 */
function generateUserData(config) {
  return `#!/bin/bash
yum update -y
yum install -y docker amazon-cloudwatch-agent
curl -sL https://rpm.nodesource.com/setup_20.x | bash -
yum install -y nodejs

# Install CloudWatch agent config
cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json << 'EOF'
{
  "metrics": {
    "namespace": "${config.projectName}",
    "metrics_collected": {
      "mem": { "measurement": ["mem_used_percent"] },
      "disk": { "measurement": ["used_percent"], "resources": ["*"] }
    }
  }
}
EOF

systemctl enable docker
systemctl start docker
systemctl enable amazon-cloudwatch-agent
systemctl start amazon-cloudwatch-agent
`
}

/**
 * Generar parámetros adicionales de base de datos
 */
export function generateDBParameters() {
  return {
    DBUsername: {
      Type: 'String',
      Default: 'dbadmin',
      Description: 'Database master username',
      MinLength: 1,
      MaxLength: 16,
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    },
    DBPassword: {
      Type: 'String',
      NoEcho: true,
      Description: 'Database master password',
      MinLength: 8,
      MaxLength: 41
    }
  }
}

/**
 * Exportar template como JSON string
 */
export function exportTemplateAsJSON(template) {
  return JSON.stringify(template, null, 2)
}

/**
 * Exportar template como YAML (simplificado)
 */
export function exportTemplateAsYAML(template) {
  let yaml = `AWSTemplateFormatVersion: "${template.AWSTemplateFormatVersion}"
Description: ${template.Description}

Parameters:\n`

  for (const [key, value] of Object.entries(template.Parameters || {})) {
    yaml += `  ${key}:\n    Type: ${value.Type}\n`
    if (value.Default) yaml += `    Default: ${value.Default}\n`
    if (value.Description) yaml += `    Description: ${value.Description}\n`
    if (value.AllowedValues) yaml += `    AllowedValues: [${value.AllowedValues.join(', ')}]\n`
  }

  yaml += `\nResources:\n`
  for (const [key, resource] of Object.entries(template.Resources || {})) {
    yaml += `  ${key}:\n    Type: ${resource.Type}\n`
    if (resource.DependsOn) yaml += `    DependsOn: ${resource.DependsOn}\n`
    yaml += `    Properties:\n`
    yaml += objectToYaml(resource.Properties, 6)
  }

  if (template.Outputs && Object.keys(template.Outputs).length > 0) {
    yaml += `\nOutputs:\n`
    for (const [key, output] of Object.entries(template.Outputs)) {
      yaml += `  ${key}:\n    Description: ${output.Description}\n    Value: ${JSON.stringify(output.Value)}\n`
    }
  }

  return yaml
}

function objectToYaml(obj, indent) {
  const spaces = ' '.repeat(indent)
  let yaml = ''

  for (const [key, value] of Object.entries(obj)) {
    if (value === undefined || value === null) continue

    if (Array.isArray(value)) {
      yaml += `${spaces}${key}:\n`
      value.forEach(item => {
        if (typeof item === 'object') {
          yaml += `${spaces}-\n${objectToYaml(item, indent + 2)}`
        } else {
          yaml += `${spaces}- ${item}\n`
        }
      })
    } else if (typeof value === 'object') {
      yaml += `${spaces}${key}:\n${objectToYaml(value, indent + 2)}`
    } else if (typeof value === 'string' && value.includes('\n')) {
      yaml += `${spaces}${key}: |\n${value.split('\n').map(l => spaces + '  ' + l).join('\n')}\n`
    } else {
      yaml += `${spaces}${key}: ${value}\n`
    }
  }

  return yaml
}
